imaGeau_linux_station: SMDExecute::SMDLauncher Class Reference
SMDExecute::SMDLauncher Class Reference
Contains all SMD properties and
different functions to communicate with the web service.
#include <SMDLauncher.h>
Public Member Functions
bool checkOrConnect ()
To check if the SMD is connected or not.
void connect ()
Connect to the server.
void debug ()
show all operation in the SMD
void disconnect ()
Disonnect to the server.
void executeAllOperation ()
Do the operation (execute the operation in the SMD)
void init ()
To initialize it with file Configuration "SMDMonitor.cfg".
bool isConnected ()
Verify if the SMD is connected or Not.
void sendOperationProgress (const uint32 id, const double value)
To send the progress for an operation.
void sendProgressTaskSMD (ProgressData *progress)
To send the progress IPC.
void sendReport (ReportData *report)
To send the report (called by executeAllOperation() and OperationsSMD::OperationAbstract::execute())
void sendVersionUpdated ()
To send the actual version of SMD.
void setRunning (bool what)
To set Runinig Variable.
SMDLauncher (const string &name, const string &url_server, const string &workspacepath)
constructor without init() (not use config/SMDMonitor.cfg)
SMDLauncher ()
Default Constructor.
void startListing ()
to start communication with others process
run the recieveMessageIpcCallBack
void whatHaveIToDo ()
Get The Operation to do from the server.
virtual ~SMDLauncher ()
Default destructor.
Static Public Member Functions
static void * receiveMessageIpcCallBack (void *parameters)
Function of thread listener for IPCS.
Static Public Attributes
static LoggerPtr logger
Private Member Functions
void getNestedMutliOperations ()
To get Detail of Operation Nested in Multi operation.
bool getVersion ()
To set a version from file 'bin/version_svn_getter.sh'.
Private Attributes
bool connected
string name
vector< OperationAbstract * > operation_to_do
the operation getted from Server
bool running
thread listener for the IPC V5 (communication_with_otherProcess)
pthread_t threadipcs
string version
string workspacepath
for Svn update workpath (to get svn info)
Detailed Description
Contains all SMD properties and
different functions to communicate with the web service.
Definition at line 37 of file SMDLauncher.h.
Constructor & Destructor Documentation
SMDLauncher::SMDLauncher (const string & name, const string & url_server, const string & workspacepath)
constructor without init() (not use config/SMDMonitor.cfg)
Returns:
Singleton of SMDLauncher
Parameters:
name name of SMD
url_server web service url
workspacepath the path that contains the shell to get the version
Definition at line 22 of file SMDLauncher.cpp.
References SMDCommunication::ISmdMonitor::setInstance().
SMDLauncher::SMDLauncher ()
Default Constructor.
Definition at line 14 of file SMDLauncher.cpp.
References init(), and SMDCommunication::ISmdMonitor::setInstance().
SMDLauncher::~SMDLauncher () [virtual]
Default destructor.
Definition at line 32 of file SMDLauncher.cpp.
References disconnect(), operation_to_do, running, and SMDCommunication::ISmdMonitor::setInstance().
Member Function Documentation
bool SMDLauncher::checkOrConnect ()
To check if the SMD is connected or not.
Returns:
Definition at line 74 of file SMDLauncher.cpp.
References connected, OperationsSMD::OperationStub::connectToServer(), logger, name, running, and SmdException::what().
Referenced by sendOperationProgress(), sendProgressTaskSMD(), sendReport(), and sendVersionUpdated().
void SMDLauncher::connect () [virtual]
Connect to the server.
Implements SMDCommunication::ISmdMonitor.
Definition at line 47 of file SMDLauncher.cpp.
References SmdException::calledBy(), connected, OperationsSMD::OperationStub::connectToServer(), INTERVAL_WAIT, logger, name, running, OperationsSMD::OperationStub::url_server, VAL_MAX_WAIT, and SmdException::what().
Referenced by main(), and OperationsSMD::SMDTest::testConnect().
void SMDLauncher::debug ()
show all operation in the SMD
Definition at line 277 of file SMDLauncher.cpp.
References name, operation_to_do, OperationsSMD::OperationStub::url_server, version, and workspacepath.
Referenced by main().
void SMDLauncher::disconnect () [virtual]
Disonnect to the server.
Implements SMDCommunication::ISmdMonitor.
Definition at line 89 of file SMDLauncher.cpp.
References SmdException::calledBy(), connected, OperationsSMD::OperationStub::connectToServer(), INTERVAL_WAIT, logger, name, threadipcs, OperationsSMD::OperationStub::url_server, VAL_MAX_WAIT, and SmdException::what().
Referenced by main(), OperationsSMD::SMDTest::testDisConnect(), and ~SMDLauncher().
void SMDLauncher::executeAllOperation () [virtual]
Do the operation (execute the operation in the SMD)
Implements SMDCommunication::ISmdMonitor.
Definition at line 265 of file SMDLauncher.cpp.
References logger, operation_to_do, and running.
Referenced by main().
void SMDLauncher::getNestedMutliOperations () [private]
To get Detail of Operation Nested in Multi operation.
Todo:
Problem with nested nested operations
Definition at line 249 of file SMDLauncher.cpp.
References OperationsSMD::OperationMulti::getNestedOperations(), operation_to_do, OperationsSMD::OperationTypeMulti, and OperationsSMD::OperationStub::retrieveOperationById().
Referenced by whatHaveIToDo().
bool SMDLauncher::getVersion () [private]
To set a version from file 'bin/version_svn_getter.sh'.
Returns:
false if this does not exist
Todo:
transformation on exception
Definition at line 356 of file SMDLauncher.cpp.
References logger, version, and workspacepath.
Referenced by sendVersionUpdated().
void SMDLauncher::init ()
To initialize it with file Configuration "SMDMonitor.cfg".
Definition at line 293 of file SMDLauncher.cpp.
References SmdException::calledBy(), name, OperationsSMD::OperationStub::url_server, and workspacepath.
Referenced by SMDLauncher().
bool SMDLauncher::isConnected () [virtual]
Verify if the SMD is connected or Not.
Returns:
true if connected, else false
Implements SMDCommunication::ISmdMonitor.
Definition at line 346 of file SMDLauncher.cpp.
References connected.
Referenced by main(), OperationsSMD::SMDTest::testConnect(), and OperationsSMD::SMDTest::testDisConnect().
void * SMDLauncher::receiveMessageIpcCallBack (void * parameters) [static]
Function of thread listener for IPCS.
Parameters:
parameters the id of communication
Definition at line 309 of file SMDLauncher.cpp.
References SmdException::calledBy(), systemcall::SmdIPCProgress::id, logger, systemcall::SmdIPCProgress::progress_value, systemcall::SmdIPCGlobalResponse::RBool, systemcall::QueueMessage::receiveSharedMessageSMD(), systemcall::SmdIPCBool::request, systemcall::SmdIPCGlobalResponse::RProgress, running, sendProgressTaskSMD(), systemcall::SmdIPCStruct_bool, systemcall::SmdIPCStruct_progress, systemcall::SmdIPCProgress::title, systemcall::SmdIPCGlobalResponse::type, and SmdException::what().
Referenced by startListing().
void SMDLauncher::sendOperationProgress (const uint32 id, const double value) [virtual]
To send the progress for an operation.
Parameters:
id id of operation
value value of progress of operation
Todo:
No exception because it's not important
Implements SMDCommunication::ISmdMonitor.
Definition at line 159 of file SMDLauncher.cpp.
References SmdException::calledBy(), checkOrConnect(), logger, and SmdException::what().
void SMDLauncher::sendProgressTaskSMD (ProgressData * progress) [virtual]
To send the progress IPC.
Parameters:
progress of the operation IPCs
Warning:
the id of progress must be unique
saved in database with id
Implements SMDCommunication::ISmdMonitor.
Definition at line 176 of file SMDLauncher.cpp.
References SmdException::calledBy(), checkOrConnect(), connected, OperationsSMD::ProgressData::id, INTERVAL_WAIT, logger, name, running, OperationsSMD::OperationStub::sendProgressSMD(), OperationsSMD::ProgressData::title, VAL_MAX_WAIT, and SmdException::what().
Referenced by receiveMessageIpcCallBack().
void SMDLauncher::sendReport (ReportData * report) [virtual]
To send the report (called by executeAllOperation() and OperationsSMD::OperationAbstract::execute())
Parameters:
report that will be send to the Server
Implements SMDCommunication::ISmdMonitor.
Definition at line 126 of file SMDLauncher.cpp.
References SmdException::calledBy(), checkOrConnect(), connected, OperationsSMD::ReportData::id, INTERVAL_WAIT, logger, running, OperationsSMD::OperationStub::sendReportData(), VAL_MAX_WAIT, and SmdException::what().
void SMDLauncher::sendVersionUpdated () [virtual]
To send the actual version of SMD.
Implements SMDCommunication::ISmdMonitor.
Definition at line 208 of file SMDLauncher.cpp.
References SmdException::calledBy(), checkOrConnect(), connected, getVersion(), INTERVAL_WAIT, logger, name, running, OperationsSMD::OperationStub::sendVersion(), VAL_MAX_WAIT, version, and SmdException::what().
Referenced by main().
void SMDLauncher::setRunning (bool what) [virtual]
To set Runinig Variable.
Implements SMDCommunication::ISmdMonitor.
Definition at line 401 of file SMDLauncher.cpp.
References running.
void SMDLauncher::startListing ()
to start communication with others process
run the recieveMessageIpcCallBack
Definition at line 351 of file SMDLauncher.cpp.
References receiveMessageIpcCallBack(), and threadipcs.
Referenced by main().
void SMDLauncher::whatHaveIToDo () [virtual]
Get The Operation to do from the server.
Implements SMDCommunication::ISmdMonitor.
Definition at line 240 of file SMDLauncher.cpp.
References getNestedMutliOperations(), name, operation_to_do, OperationsSMD::OperationStub::retrieveOperationList(), and running.
Referenced by main().
Member Data Documentation
bool SMDExecute::SMDLauncher::connected [private]
Definition at line 164 of file SMDLauncher.h.
Referenced by checkOrConnect(), connect(), disconnect(), isConnected(), sendProgressTaskSMD(), sendReport(), and sendVersionUpdated().
LoggerPtr SMDLauncher::logger [static]
Reimplemented from OperationsSMD::OperationStub.
Definition at line 64 of file SMDLauncher.h.
Referenced by checkOrConnect(), connect(), disconnect(), executeAllOperation(), getVersion(), receiveMessageIpcCallBack(), sendOperationProgress(), sendProgressTaskSMD(), sendReport(), and sendVersionUpdated().
string SMDExecute::SMDLauncher::name [private]
Definition at line 162 of file SMDLauncher.h.
Referenced by checkOrConnect(), connect(), debug(), disconnect(), init(), sendProgressTaskSMD(), sendVersionUpdated(), and whatHaveIToDo().
vector<OperationAbstract *> SMDExecute::SMDLauncher::operation_to_do [private]
the operation getted from Server
Definition at line 169 of file SMDLauncher.h.
Referenced by debug(), executeAllOperation(), getNestedMutliOperations(), whatHaveIToDo(), and ~SMDLauncher().
bool SMDExecute::SMDLauncher::running [private]
thread listener for the IPC V5 (communication_with_otherProcess)
Definition at line 177 of file SMDLauncher.h.
Referenced by checkOrConnect(), connect(), executeAllOperation(), receiveMessageIpcCallBack(), sendProgressTaskSMD(), sendReport(), sendVersionUpdated(), setRunning(), whatHaveIToDo(), and ~SMDLauncher().
pthread_t SMDExecute::SMDLauncher::threadipcs [private]
Definition at line 175 of file SMDLauncher.h.
Referenced by disconnect(), and startListing().
string SMDExecute::SMDLauncher::version [private]
Definition at line 163 of file SMDLauncher.h.
Referenced by debug(), getVersion(), and sendVersionUpdated().
string SMDExecute::SMDLauncher::workspacepath [private]
for Svn update workpath (to get svn info)
Definition at line 173 of file SMDLauncher.h.
Referenced by debug(), getVersion(), and init().
The documentation for this class was generated from the following files:
smdmonitor/src/main/launcher/SMDLauncher.h
smdmonitor/src/main/launcher/SMDLauncher.cpp