imaGeau_linux_station: OperationsSMD::SMDTest Class Reference
OperationsSMD::SMDTest Class Reference
SMD Test
.
#include <SMDTest.h>
Public Member Functions
SMDTest ()
void testConnect ()
void testDisConnect ()
void testDo_it ()
void testWhat_i_will_do ()
virtual ~SMDTest ()
Private Member Functions
CPPUNIT_TEST (testConnect)
CPPUNIT_TEST (testWhat_i_will_do)
CPPUNIT_TEST (testDo_it)
CPPUNIT_TEST (testDisConnect)
CPPUNIT_TEST_SUITE (SMDTest)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
SMD Test
.
Warning:
The Web service must be running
Definition at line 19 of file SMDTest.h.
Constructor & Destructor Documentation
SMDTest::SMDTest ()
Definition at line 16 of file SMDTest.cpp.
SMDTest::~SMDTest () [virtual]
Definition at line 21 of file SMDTest.cpp.
Member Function Documentation
OperationsSMD::SMDTest::CPPUNIT_TEST (testConnect) [private]
OperationsSMD::SMDTest::CPPUNIT_TEST (testWhat_i_will_do) [private]
OperationsSMD::SMDTest::CPPUNIT_TEST (testDo_it) [private]
OperationsSMD::SMDTest::CPPUNIT_TEST (testDisConnect) [private]
OperationsSMD::SMDTest::CPPUNIT_TEST_SUITE (SMDTest) [private]
OperationsSMD::SMDTest::CPPUNIT_TEST_SUITE_END () [private]
void SMDTest::testConnect ()
Definition at line 26 of file SMDTest.cpp.
References SMDExecute::SMDLauncher::connect(), and SMDExecute::SMDLauncher::isConnected().
void SMDTest::testDisConnect ()
Definition at line 45 of file SMDTest.cpp.
References SMDExecute::SMDLauncher::disconnect(), and SMDExecute::SMDLauncher::isConnected().
void SMDTest::testDo_it ()
Definition at line 40 of file SMDTest.cpp.
void SMDTest::testWhat_i_will_do ()
Definition at line 35 of file SMDTest.cpp.
The documentation for this class was generated from the following files:
smdmonitor/src/test/SMDTest.h
smdmonitor/src/test/SMDTest.cpp