imaGeau_linux_station: OperationsSMD::OperationSvnUpdate Class Reference
OperationsSMD::OperationSvnUpdate Class Reference
To update a repository.
#include <OperationSvnUpdate.h>
Public Member Functions
virtual void debug ()
Show all operation.
virtual void deserialize (json_spirit::Object &json_input)
OperationSvnUpdate ()
OperationSvnUpdate (uint32 _id, OperationType &_type, const string &_user, const string &_path, double _state, bool _isAchived, bool _isNested, bool report_on_success, OperationType &svn_type, const string &conflict, const string &head, bool forced)
virtual ~OperationSvnUpdate ()
Protected Member Functions
virtual ReportData * postCheck ()
verification after running operation (called by execute())
virtual ReportData * preCheck ()
verification before running operation (called by execute())
virtual ReportData * runOperation ()
To run the operation (called by execute())
Detailed Description
To update a repository.
Definition at line 18 of file OperationSvnUpdate.h.
Constructor & Destructor Documentation
OperationSvnUpdate::OperationSvnUpdate ()
Definition at line 13 of file OperationSvnUpdate.cpp.
OperationSvnUpdate::OperationSvnUpdate (uint32 _id, OperationType & _type, const string & _user, const string & _path, double _state, bool _isAchived, bool _isNested, bool report_on_success, OperationType & svn_type, const string & conflict, const string & head, bool forced)
Definition at line 19 of file OperationSvnUpdate.cpp.
OperationSvnUpdate::~OperationSvnUpdate () [virtual]
Definition at line 26 of file OperationSvnUpdate.cpp.
Member Function Documentation
void OperationSvnUpdate::debug () [virtual]
Show all operation.
Reimplemented from OperationsSMD::OperationSvn.
Definition at line 31 of file OperationSvnUpdate.cpp.
void OperationSvnUpdate::deserialize (json_spirit::Object & json_input) [virtual]
Parameters:
json_input
Reimplemented from OperationsSMD::OperationSvn.
Definition at line 37 of file OperationSvnUpdate.cpp.
References SmdException::calledBy(), OperationsSMD::OperationSMDFunctions::OperationTypeFromString(), OperationsSMD::OperationSMDFunctions::searchAttribute(), and OperationsSMD::OperationSvn::svn_type.
ReportData * OperationSvnUpdate::postCheck () [protected, virtual]
verification after running operation (called by execute())
Warning:
returned object has to be deleted
Returns:
ReportData of operation
Todo:
en cas d'ajoute des instruction if (!result->status) return result;
Reimplemented from OperationsSMD::OperationSvn.
Definition at line 100 of file OperationSvnUpdate.cpp.
References SMDCommunication::ISmdMonitor::sendVersionUpdated(), and OperationsSMD::ReportData::status.
ReportData * OperationSvnUpdate::preCheck () [protected, virtual]
verification before running operation (called by execute())
Warning:
returned object has to be deleted
Returns:
ReportData of operation
Todo:
en cas d'ajoute des instruction if (!result->status) return result;
Reimplemented from OperationsSMD::OperationSvn.
Definition at line 114 of file OperationSvnUpdate.cpp.
ReportData * OperationSvnUpdate::runOperation () [protected, virtual]
To run the operation (called by execute())
Warning:
returned object has to be deleted
Returns:
ReportData of operation
Todo:
en cas d'ajoute des instruction if (!result->status) return result;
Reimplemented from OperationsSMD::OperationSvn.
Definition at line 57 of file OperationSvnUpdate.cpp.
References OperationsSMD::OperationSvn::conflict, OperationsSMD::ReportData::contents, OperationsSMD::OperationSvn::forced, OperationsSMD::OperationSvn::head, OperationsSMD::OperationAbstract::logger, OperationsSMD::ReportData::status, and OperationsSMD::OperationAbstract::user.
The documentation for this class was generated from the following files:
smdmonitor/src/main/OperationSMD/OperationSvnUpdate.h
smdmonitor/src/main/OperationSMD/OperationSvnUpdate.cpp