imaGeau_linux_station: SmdException Class Reference
SmdException Class Reference
#include <SmdException.h>
Public Member Functions
void calledBy (const char *message, const char *file, int line)
To push the exception in the stack.
SmdException (const char *message, const char *file, int line)
Constructor with all parameters.
SmdException (const StationException &e)
virtual const char * what () const throw ()
Show the exception.
virtual ~SmdException () throw ()
Default destructor.
Private Attributes
string message
Detailed Description
Definition at line 17 of file SmdException.h.
Constructor & Destructor Documentation
SmdException::SmdException (const char * message, const char * file, int line)
Constructor with all parameters.
Parameters:
message Description of the exception
file File where the exception where detected
line Line where the exception where detected
Definition at line 10 of file SmdException.cpp.
References message.
SmdException::SmdException (const StationException & e)
Definition at line 17 of file SmdException.cpp.
SmdException::~SmdException () throw () [virtual]
Default destructor.
Definition at line 23 of file SmdException.cpp.
Member Function Documentation
void SmdException::calledBy (const char * message, const char * file, int line)
To push the exception in the stack.
Parameters:
message Description of the exception
file File where the exception where detected
line Line where the exception where detected
Definition at line 33 of file SmdException.cpp.
References message.
Referenced by SMDExecute::SMDLauncher::connect(), OperationsSMD::OperationStub::connectToServer(), OperationsSMD::OperationSvnSwitch::deserialize(), OperationsSMD::OperationSvnUpdate::deserialize(), OperationsSMD::OperationSvn::deserialize(), OperationsSMD::OperationScript::deserialize(), OperationsSMD::OperationShellFile::deserialize(), OperationsSMD::OperationMulti::deserialize(), OperationsSMD::OperationAbstract::deserialize(), OperationsSMD::OperationStub::deserializeOperationList(), SMDExecute::SMDLauncher::disconnect(), SMDExecute::SMDLauncher::init(), main(), OperationsSMD::OperationSMDFunctions::OperationFactory(), SMDExecute::SMDLauncher::receiveMessageIpcCallBack(), OperationsSMD::OperationStub::retrieveOperationById(), OperationsSMD::OperationStub::retrieveOperationList(), OperationsSMD::OperationStub::retrieveTextOperationList(), OperationsSMD::OperationStub::sendOperationProgress(), SMDExecute::SMDLauncher::sendOperationProgress(), OperationsSMD::OperationStub::sendProgressSMD(), SMDExecute::SMDLauncher::sendProgressTaskSMD(), SMDExecute::SMDLauncher::sendReport(), OperationsSMD::OperationStub::sendReportData(), OperationsSMD::OperationStub::sendVersion(), and SMDExecute::SMDLauncher::sendVersionUpdated().
const char * SmdException::what () const throw () [virtual]
Show the exception.
Returns:
SmdException::message converted in const char *
Definition at line 28 of file SmdException.cpp.
References message.
Referenced by SMDExecute::SMDLauncher::checkOrConnect(), SMDExecute::SMDLauncher::connect(), SMDExecute::SMDLauncher::disconnect(), main(), SMDExecute::SMDLauncher::receiveMessageIpcCallBack(), SMDExecute::SMDLauncher::sendOperationProgress(), SMDExecute::SMDLauncher::sendProgressTaskSMD(), SMDExecute::SMDLauncher::sendReport(), and SMDExecute::SMDLauncher::sendVersionUpdated().
Member Data Documentation
string SmdException::message [private]
Definition at line 50 of file SmdException.h.
Referenced by calledBy(), SmdException(), and what().
The documentation for this class was generated from the following files:
smdmonitor/src/main/exception/SmdException.h
smdmonitor/src/main/exception/SmdException.cpp