imaGeau_linux_station: systemcall::SignalMain Class Reference
systemcall::SignalMain Class Reference
The class that Receive the SIGNALs of the system
Example for utilization
Creating A Signal Handler.
#include <SignalMain.h>
Public Member Functions
SignalMain ()
default Constructor
virtual void waitForSignal ()
define the different signal that will be intercepted
by default the first 16 signal.
virtual ~SignalMain ()
default destructor
Static Public Member Functions
static void addFuntionForSignal (int sig, void(&fun)(void))
Attach A signal with a function
with prototype void (&fun) (void)
static void addFuntionForSignal (int sig, boost::function< void(void)> fun)
attach with boost::function() generated with CallBackFunction Example of utilization:
static void signalProcess (int signum)
call the function that will be attached for the signal
else Exit();
Static Public Attributes
static LoggerPtr logger
static map< int,
boost::function< void(void)> > signalcall
Detailed Description
The class that Receive the SIGNALs of the system
Example for utilization
Creating A Signal Handler.
 SignalMain sig;
add the different function for SIGNAL types
 sig.addFuntionForSignal (SIGINT, killed);
 sig.addFuntionForSignal (SIGKILL, killed);
 sig.addFuntionForSignal (SIGTERM, killed);
Wait for the Signals
 sig.waitForSignal ();
Signals.
 #define  SIGHUP      1  // Hangup (POSIX).
 #define  SIGINT      2  // Interrupt (ANSI).
 #define  SIGQUIT     3  // Quit (POSIX).
 #define  SIGILL      4  // Illegal instruction (ANSI).
 #define  SIGTRAP     5  // Trace trap (POSIX).
 #define  SIGABRT     6  // Abort (ANSI).
 #define  SIGIOT      6  // IOT trap (4.2 BSD).
 #define  SIGBUS      7  // BUS error (4.2 BSD).
 #define  SIGFPE      8  // Floating-point exception (ANSI).
 #define  SIGKILL     9  // Kill, unblockable (POSIX).
 #define  SIGUSR1     10 // User-defined signal 1 (POSIX).
 #define  SIGSEGV     11 // Segmentation violation (ANSI).
 #define  SIGUSR2     12 // User-defined signal 2 (POSIX).
 #define  SIGPIPE     13 // Broken pipe (POSIX).
 #define  SIGALRM     14 // Alarm clock (POSIX).
 #define  SIGTERM     15 // Termination (ANSI).
 #define  SIGSTKFLT   16 // Stack fault.
 #define  SIGCLD      SIGCHLD  // Same as SIGCHLD (System V).
 #define  SIGCHLD     17 // Child status has changed (POSIX).
 #define  SIGCONT     18 // Continue (POSIX).
 #define  SIGSTOP     19 // Stop, unblockable (POSIX).
 #define  SIGTSTP     20 // Keyboard stop (POSIX).
 #define  SIGTTIN     21 // Background read from tty (POSIX).
 #define  SIGTTOU     22 // Background write to tty (POSIX).
 #define  SIGURG      23 // Urgent condition on socket (4.2 BSD).
 #define  SIGXCPU     24 // CPU limit exceeded (4.2 BSD).
 #define  SIGXFSZ     25 // File size limit exceeded (4.2 BSD).
 #define  SIGVTALRM   26 // Virtual alarm clock (4.2 BSD).
 #define  SIGPROF     27 // Profiling alarm clock (4.2 BSD).
 #define  SIGWINCH 28 // Window size change (4.3 BSD, Sun).
 #define  SIGPOLL     SIGIO // Pollable event occurred (System V).
 #define  SIGIO    29 // I/O now possible (4.2 BSD).
 #define  SIGPWR      30 // Power failure restart (System V).
 #define SIGSYS    31 // Bad system call.
 #define SIGUNUSED 31
 #define  _NSIG    65 // Biggest signal number + 1
Definition at line 85 of file SignalMain.h.
Constructor & Destructor Documentation
SignalMain::SignalMain ()
default Constructor
Definition at line 16 of file SignalMain.cpp.
SignalMain::~SignalMain () [virtual]
default destructor
Definition at line 21 of file SignalMain.cpp.
Member Function Documentation
void SignalMain::addFuntionForSignal (int sig, void(&)(void) fun) [static]
Attach A signal with a function
with prototype void (&fun) (void)
Parameters:
sig type of signal
fun function with void (&fun) (void) prototype
Definition at line 70 of file SignalMain.cpp.
References signalcall.
Referenced by main().
void SignalMain::addFuntionForSignal (int sig, boost::function< void(void)> fun) [static]
attach with boost::function() generated with CallBackFunction Example of utilization:
 void callBacktest(MyStruct my_struct, int y , int z);
 CallBackFunction<void (&)(MyStruct,int,int)> callme (callBacktest, mystruct,y,z);
 addFuntionForSignal(SIGINT, callme.getfunctionBind() );
Parameters:
sig signal Type
fun to attach it
Definition at line 75 of file SignalMain.cpp.
References signalcall.
void SignalMain::signalProcess (int signum) [static]
call the function that will be attached for the signal
else Exit();
Parameters:
signum the type of the SIGNAL
Definition at line 50 of file SignalMain.cpp.
References logger, and signalcall.
Referenced by waitForSignal().
void SignalMain::waitForSignal () [virtual]
define the different signal that will be intercepted
by default the first 16 signal.
Definition at line 26 of file SignalMain.cpp.
References signalProcess().
Referenced by main().
Member Data Documentation
LoggerPtr SignalMain::logger [static]
Definition at line 89 of file SignalMain.h.
Referenced by signalProcess().
map< int, boost::function< void(void)> > SignalMain::signalcall [static]
Definition at line 138 of file SignalMain.h.
Referenced by addFuntionForSignal(), and signalProcess().
The documentation for this class was generated from the following files:
systemcall/src/main/SignalMain.h
systemcall/src/main/SignalMain.cpp