imaGeau_linux_station: OperationsSMD::OperationSvnSwitch Class Reference
OperationsSMD::OperationSvnSwitch Class Reference
To switch the repository to another url.
#include <OperationSvnSwitch.h>
Public Member Functions
virtual void debug ()
Show all operation.
virtual void deserialize (json_spirit::Object &json_input)
OperationSvnSwitch ()
virtual ~OperationSvnSwitch ()
Protected Member Functions
virtual ReportData * postCheck ()
verification after running operation (called by execute())
virtual ReportData * preCheck ()
verification before running operation (called by execute())
virtual ReportData * runOperation ()
To run the operation (called by execute())
Private Attributes
string url_switch
Detailed Description
To switch the repository to another url.
Definition at line 18 of file OperationSvnSwitch.h.
Constructor & Destructor Documentation
OperationSvnSwitch::OperationSvnSwitch ()
Definition at line 13 of file OperationSvnSwitch.cpp.
OperationSvnSwitch::~OperationSvnSwitch () [virtual]
Definition at line 19 of file OperationSvnSwitch.cpp.
Member Function Documentation
void OperationSvnSwitch::debug () [virtual]
Show all operation.
Reimplemented from OperationsSMD::OperationSvn.
Definition at line 23 of file OperationSvnSwitch.cpp.
References url_switch.
void OperationSvnSwitch::deserialize (json_spirit::Object & json_input) [virtual]
Parameters:
json_input
Reimplemented from OperationsSMD::OperationSvn.
Definition at line 29 of file OperationSvnSwitch.cpp.
References SmdException::calledBy(), OperationsSMD::OperationSMDFunctions::OperationTypeFromString(), OperationsSMD::OperationSMDFunctions::searchAttribute(), OperationsSMD::OperationSvn::svn_type, and url_switch.
ReportData * OperationSvnSwitch::postCheck () [protected, virtual]
verification after running operation (called by execute())
Warning:
returned object has to be deleted
Returns:
ReportData of operation
Todo:
en cas d'ajoute des instruction if (!result->status) return result;
Todo:
en cas d'ajoute des instruction if (!result->status) return result;
Reimplemented from OperationsSMD::OperationSvn.
Definition at line 66 of file OperationSvnSwitch.cpp.
ReportData * OperationSvnSwitch::preCheck () [protected, virtual]
verification before running operation (called by execute())
Warning:
returned object has to be deleted
Returns:
ReportData of operation
Todo:
en cas d'ajoute des instruction if (!result->status) return result;
Reimplemented from OperationsSMD::OperationSvn.
Definition at line 81 of file OperationSvnSwitch.cpp.
ReportData * OperationSvnSwitch::runOperation () [protected, virtual]
To run the operation (called by execute())
Warning:
returned object has to be deleted
Returns:
ReportData of operation
Todo:
en cas d'ajoute des instruction if (!result->status) return result;
Todo:
en cas d'ajoute des instruction if (!result->status) return result;
Reimplemented from OperationsSMD::OperationSvn.
Definition at line 51 of file OperationSvnSwitch.cpp.
Member Data Documentation
string OperationsSMD::OperationSvnSwitch::url_switch [private]
Definition at line 33 of file OperationSvnSwitch.h.
Referenced by debug(), and deserialize().
The documentation for this class was generated from the following files:
smdmonitor/src/main/OperationSMD/OperationSvnSwitch.h
smdmonitor/src/main/OperationSMD/OperationSvnSwitch.cpp