imaGeau_linux_station: OperationsSMD::OperationMulti Class Reference
OperationsSMD::OperationMulti Class Reference
Operation contains a List of others operations.
#include <OperationMulti.h>
Public Member Functions
virtual void debug ()
OperationAbstract::debug()
virtual void deserialize (json_spirit::Object &json_input)
OperationAbstract::deserialize(Object &json_input)
OperationAbstract * getNestedOperationById (long id)
OperationAbstract * getNestedOperationByIndex (int index)
vector< OperationAbstract * > * getNestedOperations ()
OperationMulti ()
Default Constructor.
OperationMulti (uint32 _id, OperationType _type, const string &_user, const string &_path, double _state, bool _isAchived, bool _isNested, bool report_on_success, bool fail_on_error)
Constructor for the Test Only.
virtual ~OperationMulti ()
Default destructor.
Protected Member Functions
virtual ReportData * postCheck ()
verification after running operation (called by execute())
virtual ReportData * preCheck ()
verification before running operation (called by execute())
virtual ReportData * runOperation ()
To run the operation (called by execute())
Private Attributes
bool fail_on_error
vector< OperationAbstract * > operations
Detailed Description
Operation contains a List of others operations.
Definition at line 22 of file OperationMulti.h.
Constructor & Destructor Documentation
OperationMulti::OperationMulti ()
Default Constructor.
Definition at line 12 of file OperationMulti.cpp.
OperationMulti::OperationMulti (uint32 _id, OperationType _type, const string & _user, const string & _path, double _state, bool _isAchived, bool _isNested, bool report_on_success, bool fail_on_error)
Constructor for the Test Only.
Definition at line 18 of file OperationMulti.cpp.
OperationMulti::~OperationMulti () [virtual]
Default destructor.
Definition at line 25 of file OperationMulti.cpp.
References operations.
Member Function Documentation
void OperationMulti::debug () [virtual]
OperationAbstract::debug()
Reimplemented from OperationsSMD::OperationAbstract.
Definition at line 68 of file OperationMulti.cpp.
References OperationsSMD::OperationSMDFunctions::bool_to_string(), fail_on_error, and operations.
void OperationMulti::deserialize (json_spirit::Object & json_input) [virtual]
OperationAbstract::deserialize(Object &json_input)
Reimplemented from OperationsSMD::OperationAbstract.
Definition at line 33 of file OperationMulti.cpp.
References SmdException::calledBy(), OperationsSMD::OperationAbstract::deserialize(), fail_on_error, OperationsSMD::OperationAbstract::OperationAbstract(), operations, and OperationsSMD::OperationSMDFunctions::searchAttribute().
OperationAbstract * OperationMulti::getNestedOperationById (long id)
Definition at line 78 of file OperationMulti.cpp.
References OperationsSMD::OperationAbstract::id, and operations.
OperationAbstract * OperationMulti::getNestedOperationByIndex (int index)
Definition at line 86 of file OperationMulti.cpp.
References operations.
vector< OperationAbstract * > * OperationMulti::getNestedOperations ()
Definition at line 91 of file OperationMulti.cpp.
References operations.
Referenced by SMDExecute::SMDLauncher::getNestedMutliOperations().
ReportData * OperationMulti::postCheck () [protected, virtual]
verification after running operation (called by execute())
Warning:
returned object has to be deleted
Returns:
ReportData of operation
Todo:
en cas d'ajoute des instruction if (!result->status) return result;
Reimplemented from OperationsSMD::OperationAbstract.
Definition at line 129 of file OperationMulti.cpp.
ReportData * OperationMulti::preCheck () [protected, virtual]
verification before running operation (called by execute())
Warning:
returned object has to be deleted
Returns:
ReportData of operation
Todo:
en cas d'ajoute des instruction if (!result->status) return result;
Reimplemented from OperationsSMD::OperationAbstract.
Definition at line 143 of file OperationMulti.cpp.
ReportData * OperationMulti::runOperation () [protected, virtual]
To run the operation (called by execute())
Warning:
returned object has to be deleted
Returns:
ReportData of operation
Reimplemented from OperationsSMD::OperationAbstract.
Definition at line 100 of file OperationMulti.cpp.
References OperationsSMD::ReportData::append(), OperationsSMD::ReportData::contents, OperationsSMD::OperationAbstract::inTest, OperationsSMD::OperationAbstract::logger, operations, and OperationsSMD::ReportData::status.
Member Data Documentation
bool OperationsSMD::OperationMulti::fail_on_error [private]
Definition at line 60 of file OperationMulti.h.
Referenced by debug(), and deserialize().
vector<OperationAbstract*> OperationsSMD::OperationMulti::operations [private]
Definition at line 61 of file OperationMulti.h.
Referenced by debug(), deserialize(), getNestedOperationById(), getNestedOperationByIndex(), getNestedOperations(), runOperation(), and ~OperationMulti().
The documentation for this class was generated from the following files:
smdmonitor/src/main/OperationSMD/OperationMulti.h
smdmonitor/src/main/OperationSMD/OperationMulti.cpp