imaGeau_linux_station: OperationsSMD::OperationsTest Class Reference
OperationsSMD::OperationsTest Class Reference
Test of operation CPPUNIT.
#include <OperationsTest.h>
Public Member Functions
OperationsTest ()
void testOperationScript ()
void testOperationShellFile ()
void testOperationUpdateSVN ()
virtual ~OperationsTest ()
Private Member Functions
CPPUNIT_TEST (testOperationScript)
CPPUNIT_TEST (testOperationShellFile)
CPPUNIT_TEST (testOperationUpdateSVN)
CPPUNIT_TEST_SUITE (OperationsTest)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Test of operation CPPUNIT.
Definition at line 18 of file OperationsTest.h.
Constructor & Destructor Documentation
OperationsTest::OperationsTest ()
Definition at line 18 of file OperationsTest.cpp.
OperationsTest::~OperationsTest () [virtual]
Definition at line 23 of file OperationsTest.cpp.
Member Function Documentation
OperationsSMD::OperationsTest::CPPUNIT_TEST (testOperationScript) [private]
OperationsSMD::OperationsTest::CPPUNIT_TEST (testOperationShellFile) [private]
OperationsSMD::OperationsTest::CPPUNIT_TEST (testOperationUpdateSVN) [private]
OperationsSMD::OperationsTest::CPPUNIT_TEST_SUITE (OperationsTest) [private]
OperationsSMD::OperationsTest::CPPUNIT_TEST_SUITE_END () [private]
void OperationsTest::testOperationScript ()
Definition at line 28 of file OperationsTest.cpp.
References OperationsSMD::ReportData::contents, OperationsSMD::OperationAbstract::execute(), OperationsSMD::OperationTypeScript, and OperationsSMD::OperationAbstract::setInTest().
void OperationsTest::testOperationShellFile ()
Definition at line 52 of file OperationsTest.cpp.
References OperationsSMD::ReportData::contents, OperationsSMD::OperationAbstract::execute(), OperationsSMD::OperationTypeShellFile, OperationsSMD::OperationAbstract::setInTest(), and OperationsSMD::ShellFileReplace.
void OperationsTest::testOperationUpdateSVN ()
Definition at line 80 of file OperationsTest.cpp.
References OperationsSMD::ReportData::contents, OperationsSMD::OperationAbstract::execute(), OperationsSMD::OperationTypeSvnUpdate, and OperationsSMD::OperationAbstract::setInTest().
The documentation for this class was generated from the following files:
smdmonitor/src/test/OperationsTest.h
smdmonitor/src/test/OperationsTest.cpp