imaGeau_linux_station: OperationsSMD::OperationStub Class Reference
OperationsSMD::OperationStub Class Reference
Proxy between the SMD and the Web Service Server
It use CurlCallNS::CurlCall to communicate with Web Service.
#include <OperationsStub.h>
Public Member Functions
OperationStub ()
Default Constructor.
OperationStub (const string &url_server)
a Constructor with URL of Server
virtual ~OperationStub ()
Protected Member Functions
bool connectToServer (const string &nameSMD, const bool what=true)
To connect to (or disconnect from) the Web Service.
OperationAbstract * retrieveOperationById (const long &id, const string &type)
Get Operation by ID (FOR imbriqued Operation)
OperationAbstract * retrieveOperationById (OperationAbstract *operation)
this operation it is developed to get the operation nested on the multiple operation
vector< OperationAbstract * > retrieveOperationList (const string &nameSMD)
Verify and get the operation attributed to nameSMD.
bool sendOperationProgress (const long &id_operation, const double &value)
To Send a progress operation to the server.
bool sendProgressSMD (const string &nameSMD, ProgressData *progress)
To Send a progress of other task to the server.
bool sendReportData (ReportData *report)
To Send a report to the server.
bool sendVersion (const string &nameSMD, const string &version)
To update a version in the server.
void setUrlServer (const string &url_server)
Set the url Server.
Protected Attributes
string url_server
Static Protected Attributes
static LoggerPtr logger
Private Member Functions
vector< OperationAbstract * > deserializeOperationList (const string &json_text)
Used by get operations.
string retrieveTextOperationList (const string &nameSMD)
Used by get operations.
Detailed Description
Proxy between the SMD and the Web Service Server
It use CurlCallNS::CurlCall to communicate with Web Service.
Definition at line 27 of file OperationsStub.h.
Constructor & Destructor Documentation
OperationStub::OperationStub ()
Default Constructor.
Definition at line 14 of file OperationsStub.cpp.
OperationStub::OperationStub (const string & url_server)
a Constructor with URL of Server
Parameters:
url_server url of the web service
Definition at line 19 of file OperationsStub.cpp.
OperationStub::~OperationStub () [virtual]
Definition at line 24 of file OperationsStub.cpp.
Member Function Documentation
bool OperationStub::connectToServer (const string & nameSMD, const bool what = true) [protected]
To connect to (or disconnect from) the Web Service.
connect To Server
Parameters:
nameSMD name of SMD
what true (connect), false (disconnect)
Returns:
true OK, false else
Definition at line 158 of file OperationsStub.cpp.
References OperationsSMD::OperationSMDFunctions::bool_to_string(), SmdException::calledBy(), and url_server.
Referenced by SMDExecute::SMDLauncher::checkOrConnect(), SMDExecute::SMDLauncher::connect(), and SMDExecute::SMDLauncher::disconnect().
vector< OperationAbstract * > OperationStub::deserializeOperationList (const string & json_text) [private]
Used by get operations.
Definition at line 59 of file OperationsStub.cpp.
References SmdException::calledBy(), and OperationsSMD::OperationSMDFunctions::OperationFactory().
Referenced by retrieveOperationList().
OperationAbstract * OperationStub::retrieveOperationById (const long & id, const string & type = "OperationAbstract") [protected]
Get Operation by ID (FOR imbriqued Operation)
Warning:
use the one with OperationsSMD::OperationAbstract to choose a dynamic type
or that must have a good string type Get one operation by ID
Parameters:
id that represent the operation (unique)
type of operation
Returns:
Operation
Definition at line 106 of file OperationsStub.cpp.
References SmdException::calledBy(), OperationsSMD::OperationSMDFunctions::OperationFactory(), and url_server.
Referenced by SMDExecute::SMDLauncher::getNestedMutliOperations(), and retrieveOperationById().
OperationAbstract * OperationStub::retrieveOperationById (OperationAbstract * operation) [protected]
this operation it is developed to get the operation nested on the multiple operation
Get Operation by ID (FOR imbriqued Operation)
Parameters:
operation abstract to get good operation (OperationsSMD::OperationAbstract)
Returns:
Operation
Definition at line 144 of file OperationsStub.cpp.
References OperationsSMD::OperationAbstract::getIdOperation(), OperationsSMD::OperationAbstract::getTypeOperation(), OperationsSMD::OperationSMDFunctions::OperationTypeToString(), retrieveOperationById(), and url_server.
vector< OperationAbstract * > OperationStub::retrieveOperationList (const string & nameSMD) [protected]
Verify and get the operation attributed to nameSMD.
Get Operations Associed for this SMD.
Parameters:
nameSMD the name of SMD
Returns:
Vector of operations
Definition at line 89 of file OperationsStub.cpp.
References SmdException::calledBy(), deserializeOperationList(), and retrieveTextOperationList().
Referenced by SMDExecute::SMDLauncher::whatHaveIToDo().
string OperationStub::retrieveTextOperationList (const string & nameSMD) [private]
Used by get operations.
Definition at line 39 of file OperationsStub.cpp.
References SmdException::calledBy(), and url_server.
Referenced by retrieveOperationList().
bool OperationStub::sendOperationProgress (const long & id_operation, const double & value) [protected]
To Send a progress operation to the server.
Parameters:
id_operation
value the value of progress
Returns:
Definition at line 234 of file OperationsStub.cpp.
References SmdException::calledBy(), and url_server.
bool OperationStub::sendProgressSMD (const string & nameSMD, ProgressData * progress) [protected]
To Send a progress of other task to the server.
Parameters:
nameSMD
progress OperationsSMD::OperationProgress
Returns:
Definition at line 257 of file OperationsStub.cpp.
References SmdException::calledBy(), OperationsSMD::ProgressData::id, OperationsSMD::ProgressData::title, url_server, and OperationsSMD::ProgressData::value.
Referenced by SMDExecute::SMDLauncher::sendProgressTaskSMD().
bool OperationStub::sendReportData (ReportData * report) [protected]
To Send a report to the server.
Parameters:
report OperationsSMD::ReportData
Returns:
true OK, false else
Definition at line 208 of file OperationsStub.cpp.
References OperationsSMD::OperationSMDFunctions::bool_to_string(), SmdException::calledBy(), OperationsSMD::ReportData::contents, OperationsSMD::ReportData::id, OperationsSMD::ReportData::status, and url_server.
Referenced by SMDExecute::SMDLauncher::sendReport().
bool OperationStub::sendVersion (const string & nameSMD, const string & version) [protected]
To update a version in the server.
update version in SERVER
Parameters:
nameSMD
version
Returns:
true OK, false else
Definition at line 183 of file OperationsStub.cpp.
References SmdException::calledBy(), and url_server.
Referenced by SMDExecute::SMDLauncher::sendVersionUpdated().
void OperationStub::setUrlServer (const string & url_server) [protected]
Set the url Server.
Parameters:
url_server the new url server
Definition at line 31 of file OperationsStub.cpp.
References url_server.
Member Data Documentation
LoggerPtr OperationStub::logger [static, protected]
Reimplemented in SMDExecute::SMDLauncher.
Definition at line 113 of file OperationsStub.h.
string OperationsSMD::OperationStub::url_server [protected]
Definition at line 115 of file OperationsStub.h.
Referenced by SMDExecute::SMDLauncher::connect(), connectToServer(), SMDExecute::SMDLauncher::debug(), SMDExecute::SMDLauncher::disconnect(), SMDExecute::SMDLauncher::init(), retrieveOperationById(), retrieveTextOperationList(), sendOperationProgress(), sendProgressSMD(), sendReportData(), sendVersion(), and setUrlServer().
The documentation for this class was generated from the following files:
smdmonitor/src/main/OperationSMD/OperationsStub.h
smdmonitor/src/main/OperationSMD/OperationsStub.cpp