imaGeau_linux_station: OperationsSMD::OperationSMDFunctions Class Reference
OperationsSMD::OperationSMDFunctions Class Reference
Interface of operation used in this namespace.
#include <OperationSMDFunctions.h>
Static Public Member Functions
static string bool_to_string (bool variable)
Conversion from Bool TO String.
static bool isOperationTypeOf (OperationAbstract *operation, OperationType)
test the type of operation
static OperationAbstract * OperationFactory (json_spirit::Object json_input)
generator d'operation from JSON
static OperationType OperationTypeFromString (const string &type_operation)
Conversion from enum to string.
static string OperationTypeToString (OperationType type_operation)
static json_spirit::Value searchAttribute (json_spirit::Object &obj, const string &val)
Static Public Attributes
static LoggerPtr logger
Detailed Description
Interface of operation used in this namespace.
Definition at line 22 of file OperationSMDFunctions.h.
Member Function Documentation
string OperationSMDFunctions::bool_to_string (bool variable) [static]
Conversion from Bool TO String.
Definition at line 206 of file OperationSMDFunctions.cpp.
Referenced by OperationsSMD::OperationStub::connectToServer(), OperationsSMD::OperationSvn::debug(), OperationsSMD::OperationShellFile::debug(), OperationsSMD::OperationMulti::debug(), OperationsSMD::OperationAbstract::debug(), and OperationsSMD::OperationStub::sendReportData().
bool OperationSMDFunctions::isOperationTypeOf (OperationAbstract * operation, OperationType type_operation) [static]
test the type of operation
Definition at line 161 of file OperationSMDFunctions.cpp.
References OperationsSMD::OperationTypeAbstract, OperationsSMD::OperationTypeMulti, OperationsSMD::OperationTypeScript, OperationsSMD::OperationTypeShellFile, OperationsSMD::OperationTypeSvn, OperationsSMD::OperationTypeSvnSwitch, and OperationsSMD::OperationTypeSvnUpdate.
OperationAbstract * OperationSMDFunctions::OperationFactory (json_spirit::Object json_input) [static]
generator d'operation from JSON
Definition at line 19 of file OperationSMDFunctions.cpp.
References SmdException::calledBy(), OperationsSMD::OperationAbstract::deserialize(), OperationTypeFromString(), OperationsSMD::OperationTypeMulti, OperationsSMD::OperationTypeScript, OperationsSMD::OperationTypeShellFile, OperationsSMD::OperationTypeSvn, OperationsSMD::OperationTypeSvnSwitch, OperationsSMD::OperationTypeSvnUpdate, and searchAttribute().
Referenced by OperationsSMD::OperationStub::deserializeOperationList(), and OperationsSMD::OperationStub::retrieveOperationById().
OperationType OperationSMDFunctions::OperationTypeFromString (const string & type_operation) [static]
Conversion from enum to string.
Definition at line 77 of file OperationSMDFunctions.cpp.
References OperationsSMD::OperationTypeAbstract, OperationsSMD::OperationTypeInconnu, OperationsSMD::OperationTypeMulti, OperationsSMD::OperationTypeScript, OperationsSMD::OperationTypeShellFile, OperationsSMD::OperationTypeSvn, OperationsSMD::OperationTypeSvnSwitch, and OperationsSMD::OperationTypeSvnUpdate.
Referenced by OperationsSMD::OperationSvnSwitch::deserialize(), OperationsSMD::OperationSvnUpdate::deserialize(), OperationsSMD::OperationAbstract::deserialize(), and OperationFactory().
string OperationSMDFunctions::OperationTypeToString (OperationType type_operation) [static]
Definition at line 103 of file OperationSMDFunctions.cpp.
References OperationsSMD::OperationTypeAbstract, OperationsSMD::OperationTypeMulti, OperationsSMD::OperationTypeScript, OperationsSMD::OperationTypeShellFile, OperationsSMD::OperationTypeSvn, OperationsSMD::OperationTypeSvnSwitch, and OperationsSMD::OperationTypeSvnUpdate.
Referenced by OperationsSMD::OperationSvn::debug(), OperationsSMD::OperationAbstract::debug(), OperationsSMD::OperationAbstract::execute(), and OperationsSMD::OperationStub::retrieveOperationById().
json_spirit::Value OperationSMDFunctions::searchAttribute (json_spirit::Object & obj, const string & val) [static]
Definition at line 143 of file OperationSMDFunctions.cpp.
References logger.
Referenced by OperationsSMD::OperationSvnSwitch::deserialize(), OperationsSMD::OperationSvnUpdate::deserialize(), OperationsSMD::OperationSvn::deserialize(), OperationsSMD::OperationScript::deserialize(), OperationsSMD::OperationShellFile::deserialize(), OperationsSMD::OperationMulti::deserialize(), OperationsSMD::OperationAbstract::deserialize(), and OperationFactory().
Member Data Documentation
LoggerPtr OperationSMDFunctions::logger [static]
Definition at line 25 of file OperationSMDFunctions.h.
Referenced by searchAttribute().
The documentation for this class was generated from the following files:
smdmonitor/src/main/OperationSMD/OperationSMDFunctions.h
smdmonitor/src/main/OperationSMD/OperationSMDFunctions.cpp