imaGeau_linux_station: TestSmdIPCs Class Reference
TestSmdIPCs Class Reference
#include <TestSmdIPCs.h>
Public Member Functions
void testMessageBool ()
void testMessageProgress ()
void testMessageString ()
TestSmdIPCs ()
virtual ~TestSmdIPCs ()
Private Member Functions
CPPUNIT_TEST (testMessageString)
CPPUNIT_TEST (testMessageProgress)
CPPUNIT_TEST (testMessageBool)
CPPUNIT_TEST_SUITE (TestSmdIPCs)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 17 of file TestSmdIPCs.h.
Constructor & Destructor Documentation
TestSmdIPCs::TestSmdIPCs ()
Definition at line 13 of file TestSmdIPCs.cpp.
References SMD_IPC_IDENTIFIER.
TestSmdIPCs::~TestSmdIPCs () [virtual]
Definition at line 19 of file TestSmdIPCs.cpp.
References SMD_IPC_IDENTIFIER.
Member Function Documentation
TestSmdIPCs::CPPUNIT_TEST (testMessageString) [private]
TestSmdIPCs::CPPUNIT_TEST (testMessageProgress) [private]
TestSmdIPCs::CPPUNIT_TEST (testMessageBool) [private]
TestSmdIPCs::CPPUNIT_TEST_SUITE (TestSmdIPCs) [private]
TestSmdIPCs::CPPUNIT_TEST_SUITE_END () [private]
void TestSmdIPCs::testMessageBool ()
Definition at line 68 of file TestSmdIPCs.cpp.
References systemcall::QueueMessage::messageQueueSize(), systemcall::QueueMessage::receiveSharedMessageSMD(), systemcall::SmdIPCBool::request, systemcall::QueueMessage::sendSharedMessageSMD(), and systemcall::SmdIPCStruct_bool.
void TestSmdIPCs::testMessageProgress ()
Definition at line 44 of file TestSmdIPCs.cpp.
References systemcall::SmdIPCProgress::id, systemcall::QueueMessage::messageQueueSize(), systemcall::SmdIPCProgress::progress_value, systemcall::QueueMessage::receiveSharedMessageSMD(), systemcall::QueueMessage::sendSharedMessageSMD(), systemcall::SmdIPCStruct_progress, and systemcall::SmdIPCProgress::title.
void TestSmdIPCs::testMessageString ()
Definition at line 24 of file TestSmdIPCs.cpp.
References systemcall::SmdIPCString::contents, systemcall::QueueMessage::messageQueueSize(), systemcall::QueueMessage::receiveSharedMessageSMD(), systemcall::QueueMessage::sendSharedMessageSMD(), and systemcall::SmdIPCStruct_string.
The documentation for this class was generated from the following files:
systemcall/src/test/testIPCS/TestSmdIPCs.h
systemcall/src/test/testIPCS/TestSmdIPCs.cpp