imaGeau_linux_station: systemcall::QueueMessage Class Reference
systemcall::QueueMessage Class Reference
Example of utilization:
Create and initialize String message SmdIPCString.
#include <QueueMessage.h>
Public Member Functions
defaultIPCS encapsulate (size_t size_struct, const void *data)
Converting other structures SmdIPCStructTypes on default ipcs defaultIPCS.
void killMessageQueue ()
To kill the queue message.
int messageQueueSize ()
Get the size of File message in SYSTEM IPC V of key SMD_IPC_IDENTIFIER.
QueueMessage ()
default key is SMD_IPC_IDENTIFIER
id_communications is 0
QueueMessage (long id)
QueueMessage (int key, long id)
bool receiveSharedMessage (size_t size_struct, defaultIPCS &recievedData)
recive the date sended by sendSharedMessage
Exemple for use :
Get the message from queue message
SmdIPCGlobalResponse & receiveSharedMessageSMD (SmdIPCGlobalResponse &out)
Receive a struct message SmdIPCStructTypes.
bool sendSharedMessage (size_t size_struct, void *data)
send the data that will be recived from receiveSharedMessage
bool sendSharedMessageSMD (SmdIPCStructTypes type_struct, void *data)
send a struct message SmdIPCStructTypes
virtual ~QueueMessage ()
Static Public Member Functions
static void killMessageQueue (int key)
Static function to kill the queue message.
static size_t sizeOfStructIPC (SmdIPCStructTypes type_struct)
Get the size of struct from the SmdIPCStructTypes.
Static Public Attributes
static LoggerPtr logger
For Log manipulation.
Private Attributes
long id_communications
Type of Communication.
key_t key_identifier
Key of communication in IPCs.
Detailed Description
Example of utilization:
Create and initialize String message SmdIPCString.
 SmdIPCString message;
 memset (&message, 0, sizeof(SmdIPCString));
 strcpy (message.contents, "Tableau format international");
Create an ipcs that communicate in canal 1
 QueueMessage ipcs (1);
send message
 ipcs.sendSharedMessageSMD (SmdIPCStruct_string, (void *) &testString);
receive and debug the message (to show it)
 SmdIPCGlobalResponse response = ipcs.receiveSharedMessageSMD ();
 reponse.debug();
Warning:
the canal of communication must be the same or 0 in receiver
Definition at line 57 of file QueueMessage.h.
Constructor & Destructor Documentation
QueueMessage::QueueMessage ()
default key is SMD_IPC_IDENTIFIER
id_communications is 0
Definition at line 14 of file QueueMessage.cpp.
QueueMessage::QueueMessage (long id)
Parameters:
id to initialize id_communications default key is SMD_IPC_IDENTIFIER
Definition at line 20 of file QueueMessage.cpp.
QueueMessage::QueueMessage (int key, long id)
Parameters:
key the key of communications.
id to initialize id_communications
Definition at line 26 of file QueueMessage.cpp.
QueueMessage::~QueueMessage () [virtual]
Definition at line 32 of file QueueMessage.cpp.
Member Function Documentation
defaultIPCS QueueMessage::encapsulate (size_t size_struct, const void * data)
Converting other structures SmdIPCStructTypes on default ipcs defaultIPCS.
Parameters:
size_struct size of Struct
data any structure
Returns:
defaultIPCS
Definition at line 257 of file QueueMessage.cpp.
References id_communications, systemcall::defaultIPCS::mtext, and systemcall::defaultIPCS::mtype.
Referenced by sendSharedMessage(), and sendSharedMessageSMD().
void QueueMessage::killMessageQueue ()
To kill the queue message.
Definition at line 269 of file QueueMessage.cpp.
References key_identifier.
void QueueMessage::killMessageQueue (int key) [static]
Static function to kill the queue message.
Parameters:
key identifier of Queue Message
Definition at line 274 of file QueueMessage.cpp.
References logger.
int QueueMessage::messageQueueSize ()
Get the size of File message in SYSTEM IPC V of key SMD_IPC_IDENTIFIER.
Returns:
size of file message
Definition at line 238 of file QueueMessage.cpp.
References key_identifier, and logger.
Referenced by TestSmdIPCs::testMessageBool(), TestSmdIPCs::testMessageProgress(), and TestSmdIPCs::testMessageString().
bool QueueMessage::receiveSharedMessage (size_t size_struct, defaultIPCS & recievedData)
recive the date sended by sendSharedMessage
Exemple for use :
Get the message from queue message
  defaultIPCS response;
 queuemessage.receiveSharedMessage(sizeof(MyStruct),response);
the cast of struct
 MyStruct my_struct;
 my_struct = *((MyStruct *) response.mtext);
Parameters:
size_struct the size of struct must be the same in the function sended
recievedData it will content the response
Returns:
true if OK, false else
Definition at line 154 of file QueueMessage.cpp.
References id_communications, key_identifier, and logger.
SmdIPCGlobalResponse & QueueMessage::receiveSharedMessageSMD (SmdIPCGlobalResponse & out)
Receive a struct message SmdIPCStructTypes.
Returns:
the struct message
Definition at line 91 of file QueueMessage.cpp.
References id_communications, key_identifier, logger, systemcall::SmdIPCGlobalResponse::RBool, systemcall::SmdIPCGlobalResponse::RProgress, systemcall::SmdIPCGlobalResponse::RString, systemcall::SmdIPCGlobal::size, systemcall::SmdIPCStruct_bool, systemcall::SmdIPCStruct_progress, systemcall::SmdIPCStruct_string, systemcall::SmdIPCGlobalResponse::type, and systemcall::SmdIPCGlobal::type_Ipc_struct.
Referenced by SMDExecute::SMDLauncher::receiveMessageIpcCallBack(), TestSmdIPCs::testMessageBool(), TestSmdIPCs::testMessageProgress(), and TestSmdIPCs::testMessageString().
bool QueueMessage::sendSharedMessage (size_t size_struct, void * data)
send the data that will be recived from receiveSharedMessage
Warning:
Becarful when you use this function
Parameters:
size_struct size of the struct to send
data that can be any STRUCT without virtual Attributes.
Returns:
true if OK, false else
Definition at line 188 of file QueueMessage.cpp.
References encapsulate(), id_communications, key_identifier, and logger.
bool QueueMessage::sendSharedMessageSMD (SmdIPCStructTypes type_struct, void * data)
send a struct message SmdIPCStructTypes
Warning:
The type_struct and data must have the same TYPE
else error in USE
Parameters:
type_struct type of struct SmdIPCStructTypes
data the data to Send
Returns:
Definition at line 37 of file QueueMessage.cpp.
References encapsulate(), id_communications, key_identifier, logger, systemcall::SmdIPCGlobal::size, sizeOfStructIPC(), and systemcall::SmdIPCGlobal::type_Ipc_struct.
Referenced by killed(), main(), TestSmdIPCs::testMessageBool(), TestSmdIPCs::testMessageProgress(), and TestSmdIPCs::testMessageString().
size_t QueueMessage::sizeOfStructIPC (SmdIPCStructTypes type_struct) [static]
Get the size of struct from the SmdIPCStructTypes.
Returns:
size of struct that match with the type givend
Definition at line 218 of file QueueMessage.cpp.
References systemcall::SmdIPCStruct_bool, systemcall::SmdIPCStruct_global, systemcall::SmdIPCStruct_progress, and systemcall::SmdIPCStruct_string.
Referenced by sendSharedMessageSMD().
Member Data Documentation
long systemcall::QueueMessage::id_communications [private]
Type of Communication.
Definition at line 172 of file QueueMessage.h.
Referenced by encapsulate(), receiveSharedMessage(), receiveSharedMessageSMD(), sendSharedMessage(), and sendSharedMessageSMD().
key_t systemcall::QueueMessage::key_identifier [private]
Key of communication in IPCs.
Todo:
Ajouter 2 fonction qui permet d'envoyer et de recevoir ce n'import quel structure
Definition at line 168 of file QueueMessage.h.
Referenced by killMessageQueue(), messageQueueSize(), receiveSharedMessage(), receiveSharedMessageSMD(), sendSharedMessage(), and sendSharedMessageSMD().
LoggerPtr QueueMessage::logger [static]
For Log manipulation.
Definition at line 64 of file QueueMessage.h.
Referenced by killMessageQueue(), messageQueueSize(), receiveSharedMessage(), receiveSharedMessageSMD(), sendSharedMessage(), and sendSharedMessageSMD().
The documentation for this class was generated from the following files:
systemcall/src/main/QueueMessage.h
systemcall/src/main/QueueMessage.cpp