imaGeau_linux_station: SMDCommunication::ISmdMonitor Class Reference
SMDCommunication::ISmdMonitor Class Reference
imaGeau::ISmdMonitor
#include <ISmdMonitor.h>
Public Member Functions
virtual void connect ()=0
Connect to the server.
virtual void disconnect ()=0
Disonnect to the server.
virtual void executeAllOperation ()=0
Do the operation (execute the operation in the SMD)
virtual bool isConnected ()=0
Verify if the SMD is connected or Not.
virtual void sendOperationProgress (const uint32 id, const double value)=0
To send the progress for an operation.
virtual void sendProgressTaskSMD (ProgressData *progress)=0
To send the progress IPC.
virtual void sendReport (ReportData *report)=0
To send the report (called by executeAllOperation() and OperationsSMD::OperationAbstract::execute())
virtual void sendVersionUpdated ()=0
To send the actual version of SMD.
virtual void setRunning (bool what)=0
Set Value of Running.
virtual void whatHaveIToDo ()=0
Get The Operation to do from the server.
virtual ~ISmdMonitor ()
Static Public Member Functions
static ISmdMonitor * getInstance ()
static void setInstance (ISmdMonitor *mon)
Static Private Attributes
static ISmdMonitor * instance
Detailed Description
imaGeau::ISmdMonitor
Since:
12 juil. 2012
Author:
bdm
Definition at line 23 of file ISmdMonitor.h.
Constructor & Destructor Documentation
ISmdMonitor::~ISmdMonitor () [virtual]
Definition at line 17 of file ISmdMonitor.cpp.
Member Function Documentation
virtual void SMDCommunication::ISmdMonitor::connect () [pure virtual]
Connect to the server.
Implemented in SMDExecute::SMDLauncher.
virtual void SMDCommunication::ISmdMonitor::disconnect () [pure virtual]
Disonnect to the server.
Implemented in SMDExecute::SMDLauncher.
virtual void SMDCommunication::ISmdMonitor::executeAllOperation () [pure virtual]
Do the operation (execute the operation in the SMD)
Implemented in SMDExecute::SMDLauncher.
ISmdMonitor * ISmdMonitor::getInstance () [static]
Definition at line 12 of file ISmdMonitor.cpp.
References instance.
virtual bool SMDCommunication::ISmdMonitor::isConnected () [pure virtual]
Verify if the SMD is connected or Not.
Returns:
true if connected, else false
Implemented in SMDExecute::SMDLauncher.
virtual void SMDCommunication::ISmdMonitor::sendOperationProgress (const uint32 id, const double value) [pure virtual]
To send the progress for an operation.
Parameters:
id id of operation
value value of progress of operation
Implemented in SMDExecute::SMDLauncher.
virtual void SMDCommunication::ISmdMonitor::sendProgressTaskSMD (ProgressData * progress) [pure virtual]
To send the progress IPC.
Parameters:
progress of the operation IPCs
Warning:
the id of progress must be unique
saved in database with id
Implemented in SMDExecute::SMDLauncher.
virtual void SMDCommunication::ISmdMonitor::sendReport (ReportData * report) [pure virtual]
To send the report (called by executeAllOperation() and OperationsSMD::OperationAbstract::execute())
Parameters:
report that will be send to the Server
Implemented in SMDExecute::SMDLauncher.
virtual void SMDCommunication::ISmdMonitor::sendVersionUpdated () [pure virtual]
To send the actual version of SMD.
Implemented in SMDExecute::SMDLauncher.
Referenced by OperationsSMD::OperationSvnUpdate::postCheck().
void ISmdMonitor::setInstance (ISmdMonitor * mon) [static]
Definition at line 7 of file ISmdMonitor.cpp.
References instance.
Referenced by SMDExecute::SMDLauncher::SMDLauncher(), and SMDExecute::SMDLauncher::~SMDLauncher().
virtual void SMDCommunication::ISmdMonitor::setRunning (bool what) [pure virtual]
Set Value of Running.
Parameters:
what
Implemented in SMDExecute::SMDLauncher.
virtual void SMDCommunication::ISmdMonitor::whatHaveIToDo () [pure virtual]
Get The Operation to do from the server.
Implemented in SMDExecute::SMDLauncher.
Member Data Documentation
ISmdMonitor * ISmdMonitor::instance [static, private]
Definition at line 90 of file ISmdMonitor.h.
Referenced by getInstance(), and setInstance().
The documentation for this class was generated from the following files:
smdmonitor/src/main/communication/ISmdMonitor.h
smdmonitor/src/main/communication/ISmdMonitor.cpp