imaGeau_linux_station: OperationsSMD::OperationSvn Class Reference
OperationsSMD::OperationSvn Class Reference
for the SVN Operation
#include <OperationSvn.h>
Public Member Functions
virtual void debug ()
Show all operation.
virtual void deserialize (json_spirit::Object &json_input)
OperationType getSvnType ()
OperationSvn ()
OperationSvn (uint32 _id, OperationType &_type, const string &_user, const string &_path, double _state, bool _isAchived, bool _isNested, bool report_on_success, OperationType &svn_type, const string &conflict, const string &head, bool forced)
virtual ~OperationSvn ()
Static Public Member Functions
static string getConflictFromString (const string &type)
ConflictAction String To Enum.
static bool svn_line_validator (const string &line)
static bool version_line_getter (const string &line, string &version)
Protected Member Functions
virtual ReportData * postCheck ()
verification after running operation (called by execute())
virtual ReportData * preCheck ()
verification before running operation (called by execute())
virtual ReportData * runOperation ()
To run the operation (called by execute())
Protected Attributes
string conflict
bool forced
string head
OperationType svn_type
Detailed Description
for the SVN Operation
Definition at line 18 of file OperationSvn.h.
Constructor & Destructor Documentation
OperationSvn::OperationSvn ()
Definition at line 13 of file OperationSvn.cpp.
OperationSvn::OperationSvn (uint32 _id, OperationType & _type, const string & _user, const string & _path, double _state, bool _isAchived, bool _isNested, bool report_on_success, OperationType & svn_type, const string & conflict, const string & head, bool forced)
Definition at line 19 of file OperationSvn.cpp.
OperationSvn::~OperationSvn () [virtual]
Definition at line 26 of file OperationSvn.cpp.
Member Function Documentation
void OperationSvn::debug () [virtual]
Show all operation.
Reimplemented from OperationsSMD::OperationAbstract.
Reimplemented in OperationsSMD::OperationSvnUpdate, and OperationsSMD::OperationSvnSwitch.
Definition at line 31 of file OperationSvn.cpp.
References OperationsSMD::OperationSMDFunctions::bool_to_string(), conflict, forced, getConflictFromString(), head, OperationsSMD::OperationSMDFunctions::OperationTypeToString(), and svn_type.
void OperationSvn::deserialize (json_spirit::Object & json_input) [virtual]
Parameters:
json_input
Reimplemented from OperationsSMD::OperationAbstract.
Reimplemented in OperationsSMD::OperationSvnUpdate, and OperationsSMD::OperationSvnSwitch.
Definition at line 41 of file OperationSvn.cpp.
References SmdException::calledBy(), conflict, forced, getConflictFromString(), head, and OperationsSMD::OperationSMDFunctions::searchAttribute().
string OperationSvn::getConflictFromString (const string & type) [static]
ConflictAction String To Enum.
Definition at line 127 of file OperationSvn.cpp.
Referenced by debug(), and deserialize().
OperationType OperationSvn::getSvnType ()
Definition at line 122 of file OperationSvn.cpp.
References svn_type.
ReportData * OperationSvn::postCheck () [protected, virtual]
verification after running operation (called by execute())
Warning:
returned object has to be deleted
Returns:
ReportData of operation
Todo:
en cas d'ajoute des instruction if (!result->status) return result;
Reimplemented from OperationsSMD::OperationAbstract.
Reimplemented in OperationsSMD::OperationSvnUpdate, and OperationsSMD::OperationSvnSwitch.
Definition at line 76 of file OperationSvn.cpp.
ReportData * OperationSvn::preCheck () [protected, virtual]
verification before running operation (called by execute())
Warning:
returned object has to be deleted
Returns:
ReportData of operation
Reimplemented from OperationsSMD::OperationAbstract.
Reimplemented in OperationsSMD::OperationSvnUpdate, and OperationsSMD::OperationSvnSwitch.
Definition at line 90 of file OperationSvn.cpp.
References OperationsSMD::ReportData::contents, OperationsSMD::OperationAbstract::logger, OperationsSMD::OperationAbstract::path, OperationsSMD::ReportData::status, svn_line_validator(), and OperationsSMD::OperationAbstract::user.
ReportData * OperationSvn::runOperation () [protected, virtual]
To run the operation (called by execute())
Warning:
returned object has to be deleted
Returns:
ReportData of operation
Todo:
en cas d'ajoute des instruction if (!result->status) return result;
Reimplemented from OperationsSMD::OperationAbstract.
Reimplemented in OperationsSMD::OperationSvnUpdate, and OperationsSMD::OperationSvnSwitch.
Definition at line 62 of file OperationSvn.cpp.
bool OperationSvn::svn_line_validator (const string & line) [static]
Definition at line 140 of file OperationSvn.cpp.
References OperationsSMD::OperationAbstract::logger.
Referenced by preCheck().
bool OperationSvn::version_line_getter (const string & line, string & version) [static]
Parameters:
line
version output param
Returns:
Definition at line 151 of file OperationSvn.cpp.
References OperationsSMD::OperationAbstract::logger.
Member Data Documentation
string OperationsSMD::OperationSvn::conflict [protected]
Definition at line 52 of file OperationSvn.h.
Referenced by debug(), deserialize(), and OperationsSMD::OperationSvnUpdate::runOperation().
bool OperationsSMD::OperationSvn::forced [protected]
Definition at line 53 of file OperationSvn.h.
Referenced by debug(), deserialize(), and OperationsSMD::OperationSvnUpdate::runOperation().
string OperationsSMD::OperationSvn::head [protected]
Definition at line 51 of file OperationSvn.h.
Referenced by debug(), deserialize(), and OperationsSMD::OperationSvnUpdate::runOperation().
OperationType OperationsSMD::OperationSvn::svn_type [protected]
Definition at line 50 of file OperationSvn.h.
Referenced by debug(), OperationsSMD::OperationSvnSwitch::deserialize(), OperationsSMD::OperationSvnUpdate::deserialize(), and getSvnType().
The documentation for this class was generated from the following files:
smdmonitor/src/main/OperationSMD/OperationSvn.h
smdmonitor/src/main/OperationSMD/OperationSvn.cpp