imaGeau_linux_station: smdmonitor/src/main/launcher/main.cpp File Reference
smdmonitor/src/main/launcher/main.cpp File Reference
#include "SMDLauncher.h"
#include "Properties.h"
#include "CallBackFunction.h"
#include "SignalMain.h"
Functions
void killed ()
int main ()
Function Documentation
void killed ()
Definition at line 9 of file main.cpp.
References systemcall::SmdIPCBool::request, systemcall::QueueMessage::sendSharedMessageSMD(), and systemcall::SmdIPCStruct_bool.
Referenced by main().
int main ()
Definition at line 22 of file main.cpp.
References systemcall::SignalMain::addFuntionForSignal(), SmdException::calledBy(), SMDExecute::SMDLauncher::connect(), SMDExecute::SMDLauncher::debug(), SMDExecute::SMDLauncher::disconnect(), SMDExecute::SMDLauncher::executeAllOperation(), SMDExecute::SMDLauncher::isConnected(), killed(), SMDExecute::SMDLauncher::sendVersionUpdated(), SMDExecute::SMDLauncher::startListing(), systemcall::SignalMain::waitForSignal(), SmdException::what(), and SMDExecute::SMDLauncher::whatHaveIToDo().