LIB_NAME = operationSMD

CPP_FILES = $(shell find . -maxdepth 1 -iname '*.cpp')


SHARED_LIBRARIES += curlCall
SHARED_LIBRARIES += SmdExecption
SHARED_LIBRARIES += json_spirit
SHARED_LIBRARIES += common
SHARED_LIBRARIES += log4cxx
SHARED_LIBRARIES += pthread
SHARED_LIBRARIES += systemcall

include $(ROOT_DIR)/Rules.make
