SHARED_LIBRARIES += log4cxx
SHARED_LIBRARIES += cppunit
SHARED_LIBRARIES += common

CPP_FILES = $(shell find . -maxdepth 1 -iname '*.cpp')

EXECUTABLE_NAME = TestRunner_common

include $(ROOT_DIR)/Rules.make
